#!/usr/bin/env bash
# Collect the sky130_fd_sc_hd simulation models that results/.../6_final.v needs.
#
# Why this exists: ORFS's sky130hd platform ships no standard-cell Verilog
# models and no sky130 PDK is installed on this machine (see flow/README.md).
# Icarus is the Phase 4 gate-level simulator (cocotb 2.1.0 rejects the local
# Verilator 5.032), and Icarus needs real behavioural models plus `specify`
# blocks for SDF back-annotation.
#
# The upstream cell files `include their siblings by REPO-RELATIVE path
# (e.g. ../../models/udp_dff_p/sky130_fd_sc_hd__udp_dff_p.v), so this script
# mirrors the upstream directory layout exactly. Flattening it breaks them.
#
# Output: flow/gl_models/sky130_fd_sc_hd.v  - includes every cell the netlist
#         actually instantiates, plus the UDP primitives they pull in.
#
# Usage:  flow/make_gl_models.sh [path-to-6_final.v]
set -euo pipefail

PROJ=/home/pgratz/pcie-matmul
NETLIST=${1:-$PROJ/results/sky130hd/pcie_matmul/base/6_final.v}
OUT=$PROJ/flow/gl_models
RAW=https://raw.githubusercontent.com/google/skywater-pdk-libs-sky130_fd_sc_hd/main

[ -f "$NETLIST" ] || { echo "no netlist at $NETLIST" >&2; exit 1; }
rm -rf "$OUT/cells" "$OUT/models"
mkdir -p "$OUT/cells" "$OUT/models"

# Instantiations look like:  sky130_fd_sc_hd__nand2_1 _1234_ (...);
# The model directory is the BASE cell, drive-strength stripped: nand2_1 -> nand2
# FULL is the strength-qualified name the netlist actually instantiates
# (e.g. fa_1); BASE is the model directory (fa). Upstream ships both:
# cells/fa/sky130_fd_sc_hd__fa.v defines the generic module, and
# cells/fa/sky130_fd_sc_hd__fa_1.v defines the strength-qualified one that
# the netlist needs. Fetching only the base leaves every instance unresolved.
mapfile -t FULL < <(grep -oE 'sky130_fd_sc_hd__[a-z0-9_]+' "$NETLIST" \
    | sed -E 's/^sky130_fd_sc_hd__//' | sort -u)
mapfile -t CELLS < <(printf '%s\n' "${FULL[@]}" | sed -E 's/_[0-9]+$//' | sort -u)
echo "netlist uses ${#FULL[@]} strength-qualified cells over ${#CELLS[@]} base cells"

# Per cell, fetch the umbrella .v and every variant it may `include.
SUFFIXES=(functional functional.pp behavioral behavioral.pp specify
          blackbox pp.blackbox symbol pp.symbol)
for c in "${CELLS[@]}"; do
  mkdir -p "$OUT/cells/$c"
  curl -fsS "$RAW/cells/$c/sky130_fd_sc_hd__$c.v" \
       -o "$OUT/cells/$c/sky130_fd_sc_hd__$c.v" \
    || { echo "FAILED to fetch cell $c" >&2; exit 1; }
  for sfx in "${SUFFIXES[@]}"; do
    curl -fsS "$RAW/cells/$c/sky130_fd_sc_hd__$c.$sfx.v" \
         -o "$OUT/cells/$c/sky130_fd_sc_hd__$c.$sfx.v" 2>/dev/null \
      || rm -f "$OUT/cells/$c/sky130_fd_sc_hd__$c.$sfx.v"
  done
done

# Strength-qualified wrappers, e.g. cells/fa/sky130_fd_sc_hd__fa_1.v
for f in "${FULL[@]}"; do
  b=$(printf '%s' "$f" | sed -E 's/_[0-9]+$//')
  [ "$f" = "$b" ] && continue
  curl -fsS "$RAW/cells/$b/sky130_fd_sc_hd__$f.v" \
       -o "$OUT/cells/$b/sky130_fd_sc_hd__$f.v" \
    || { echo "FAILED to fetch strength variant $f" >&2; exit 1; }
done

# Resolve ../../models/<m>/... includes transitively until nothing new appears.
for pass in 1 2 3; do
  new=0
  mapfile -t MODELS < <(grep -rhoE '\.\./\.\./models/[a-z0-9_]+/' "$OUT/cells" "$OUT/models" 2>/dev/null \
      | sed -E 's|\.\./\.\./models/||; s|/$||' | sort -u)
  for m in "${MODELS[@]:-}"; do
    [ -d "$OUT/models/$m" ] && continue
    mkdir -p "$OUT/models/$m"; new=1
    curl -fsS "$RAW/models/$m/sky130_fd_sc_hd__$m.v" \
         -o "$OUT/models/$m/sky130_fd_sc_hd__$m.v" \
      || { echo "FAILED to fetch model $m" >&2; exit 1; }
    for sfx in "${SUFFIXES[@]}"; do
      curl -fsS "$RAW/models/$m/sky130_fd_sc_hd__$m.$sfx.v" \
           -o "$OUT/models/$m/sky130_fd_sc_hd__$m.$sfx.v" 2>/dev/null \
        || rm -f "$OUT/models/$m/sky130_fd_sc_hd__$m.$sfx.v"
    done
  done
  [ "$new" = 0 ] && break
done

{ echo "// generated by flow/make_gl_models.sh - do not edit"
  echo "// sky130_fd_sc_hd models for the cells in $(basename "$NETLIST")"
  echo "\`ifndef SKY130_FD_SC_HD_V"
  echo "\`define SKY130_FD_SC_HD_V"
  for f in "${FULL[@]}"; do
    b=$(printf '%s' "$f" | sed -E 's/_[0-9]+$//')
    echo "\`include \"cells/$b/sky130_fd_sc_hd__$f.v\""
  done
  echo "\`endif"
} > "$OUT/sky130_fd_sc_hd.v"

echo "wrote $OUT/sky130_fd_sc_hd.v"
echo "cells: $(ls "$OUT/cells" | wc -l) base dirs, ${#FULL[@]} strength variants;   models: $(ls "$OUT/models" | wc -l)"
cat <<'USAGE'

Compile under Icarus FROM flow/gl_models (the relative includes require it):

  cd flow/gl_models
  INC=$(for d in cells/*/ models/*/; do printf -- "-I%s " "$d"; done)
  iverilog -g2012 -DFUNCTIONAL -DUNIT_DELAY="" $INC \
      -o gl.vvp -s matmul_top \
      sky130_fd_sc_hd.v \
      ../../results/sky130hd/pcie_matmul/base/6_final.v <your tb files>

For SDF back-annotation drop -DFUNCTIONAL (the specify blocks live in the
non-functional variant) and use $sdf_annotate with
results/sky130hd/pcie_matmul/base/6_final.sdf.
USAGE
